export const START_TRACKING = "START_TRACKING";
export const STOP_TRACKING = "STOP_TRACKING";
export const CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION";
export const CHANGE_PROJECT = "CHANGE_PROJECT";
export const LOAD_CURRENT_TIME_ENTRY = "LOAD_CURRENT_TIME_ENTRY";
