export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const LOAD_TIME_ENTRIES = "LOAD_TIME_ENTRIES";
export const LOAD_CURRENT_TIME_ENTRY = "LOAD_CURRENT_TIME_ENTRY";
export const START_TRACKING = "START_TRACKING";
export const STOP_TRACKING = "STOP_TRACKING";
export const OPEN_CREATE_PROJECT_MODAL = "OPEN_CREATE_PROJECT_MODAL";
export const CLOSE_CREATE_PROJECT_MODAL = "CLOSE_CREATE_PROJECT_MODAL";

export const CHANGE_PROJECT = "CHANGE_PROJECT";
export const CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION";
