export const OPEN_CREATE_PROJECT_MODAL = "OPEN_CREATE_PROJECT_MODAL";
export const CLOSE_CREATE_PROJECT_MODAL = "CLOSE_CREATE_PROJECT_MODAL";
export const SET_ADD_PROJECT_MODAL_ERROR = "SET_ADD_PROJECT_MODAL_ERROR";
export const CLEAR_ADD_PROJECT_MODAL_ERROR = "CLEAR_ADD_PROJECT_MODAL_ERROR";
